clone:
  depth: full
pipelines:
  branches:
    main:
      - step:
          script:
             - git remote add sync git@github.com:lokeswari-mm/test-mirror-mm.git
             - git checkout bitbucket-main
             - git pull    
             - git push sync bitbucket-main
             
           