clone:
  depth: full
pipelines:
  branches:
    dev:
      - step:
          script:
             - git remote add sync git@github.com:lokeswari-mm/test-mirror-mm.git
             - git checkout dev
             - git pull    
             - git push sync dev
             
           